[build]
  publish = "apps/react-app/build"
  command = "cd ../../ && npm -v && npm i && npm run build -w @zgriesinger/react-app"

  [build.environment]
    REACT_APP_CAMELIFY_VERSION = "one"
    NPM_CONFIG_ONLY = "development"
    NPM_VERSION = "7.20.1"
