[build]
  publish = "apps/react-app/build"
  command = "../../../ && NPM_CONFIG_DRY_RUN=false NPM_CONFIG_ONLY=null npm i && npm run build -w @zgriesinger/react-app"
  [build.environment]
    NPM_VERSION = "7.20.1"
    NPM_CONFIG_DRY_RUN = "true"
    NPM_CONFIG_ONLY = "development"
    NPM_CONFIG_NO_AUDIT = "true"
